import type {
  Data_UsableItem,
  Enemy_Action,
  ItemEffect,
} from "@sigureya/rpgtypes";
import type { Game_Unit } from "./Game_Unit";
import type { IUnit, IUsableItem, IBattler } from "./types/";
// -----------------------------------------------------------------------------
// Game_Action
//
// The game object class for a battle action.
export declare class Game_Action {
  _subjectActorId: number;
  _subjectEnemyIndex: number;
  _forcing: boolean;
  _item: IUsableItem;
  _targetIndex: number;
  _reflectionTarget?: IBattler;
  static EFFECT_RECOVER_HP: 11;
  static EFFECT_RECOVER_MP: 12;
  static EFFECT_GAIN_TP: 13;
  static EFFECT_ADD_STATE: 21;
  static EFFECT_REMOVE_STATE: 22;
  static EFFECT_ADD_BUFF: 31;
  static EFFECT_ADD_DEBUFF: 32;
  static EFFECT_REMOVE_BUFF: 33;
  static EFFECT_REMOVE_DEBUFF: 34;
  static EFFECT_SPECIAL: 41;
  static EFFECT_GROW: 42;
  static EFFECT_LEARN_SKILL: 43;
  static EFFECT_COMMON_EVENT: 44;
  static SPECIAL_EFFECT_ESCAPE: 0;
  static HITTYPE_CERTAIN: 0;
  static HITTYPE_PHYSICAL: 1;
  static HITTYPE_MAGICAL: 2;
  constructor(subject: IBattler, forcing: boolean);
  constructor(subject: IBattler);
  initialize(subject: IBattler, forcing: boolean): void;
  clear(): void;
  setSubject(subject: IBattler): void;
  subject(): IBattler;
  friendsUnit(): IUnit<IBattler>;
  opponentsUnit(): IUnit<IBattler>;
  setEnemyAction(action: Enemy_Action): void;
  setAttack(): void;
  setGuard(): void;
  setSkill(skillId: number): void;
  setItem(itemId: number): void;
  setItemObject(object: Data_UsableItem): void;
  setTarget(targetIndex: number): void;
  item(): Data_UsableItem | null;
  isSkill(): boolean;
  isItem(): boolean;
  numRepeats(): number;
  checkItemScope(list: ReadonlyArray<number>): boolean;
  isForOpponent(): boolean;
  isForFriend(): boolean;
  isForEveryone(): boolean;
  isForAliveFriend(): boolean;
  isForDeadFriend(): boolean;
  isForUser(): boolean;
  isForOne(): boolean;
  isForRandom(): boolean;
  isForAll(): boolean;
  needsSelection(): boolean;
  numTargets(): number;
  checkDamageType(list: ReadonlyArray<number>): boolean;
  isHpEffect(): boolean;
  isMpEffect(): boolean;
  isDamage(): boolean;
  isRecover(): boolean;
  isDrain(): boolean;
  isHpRecover(): boolean;
  isMpRecover(): boolean;
  isCertainHit(): boolean;
  isPhysical(): boolean;
  isMagical(): boolean;
  isAttack(): boolean;
  isGuard(): boolean;
  isMagicSkill(): boolean;
  decideRandomTarget(): void;
  setConfusion(): void;
  prepare(): void;
  isValid(): boolean;
  speed(): number;
  makeTargets(): IBattler[];
  repeatTargets(targets: IBattler[]): IBattler[];
  confusionTarget(): IBattler;
  targetsForEveryone(): IBattler[];
  targetsForOpponents(): IBattler[];
  targetsForFriends(): IBattler[];
  randomTargets(unit: IUnit<IBattler>): IBattler[];
  targetsForDead(unit: Game_Unit): IBattler[];
  targetsForAlive(unit: IUnit<IBattler>): IBattler[];
  targetsForDeadAndAlive(unit: Game_Unit): IBattler[];
  evaluate(): number;
  itemTargetCandidates(): number;
  evaluateWithTarget(target: IBattler): number;
  testApply(target: IBattler): boolean;
  testLifeAndDeath(target: IBattler): boolean;
  hasItemAnyValidEffects(target: IBattler): boolean;
  testItemEffect(target: IBattler, effect: ItemEffect): boolean;
  itemCnt(target: IBattler): number;
  itemMrf(target: IBattler): number;
  itemHit(battler: IBattler): number;
  itemEva(target: IBattler): number;
  itemCri(target: IBattler): number;
  apply(target: IBattler): void;
  makeDamageValue(target: IBattler, critical: boolean): number;
  evalDamageFormula(target: IBattler): number;
  calcElementRate(target: IBattler): number;
  elementsMaxRate(target: IBattler, elements: number[]): number;
  applyCritical(damage: number): number;
  applyVariance(damage: number, variance: number): number;
  applyGuard(damage: number, target: IBattler): number;
  executeDamage(target: IBattler, value: number): void;
  executeHpDamage(target: IBattler, value: number): void;
  executeMpDamage(target: IBattler, value: number): void;
  gainDrainedHp(value: number): void;
  gainDrainedMp(value: number): void;
  applyItemEffect(taget: IBattler, effect: ItemEffect): void;
  itemEffectRecoverHp(taget: IBattler, effect: ItemEffect): void;
  itemEffectRecoverMp(taget: IBattler, effect: ItemEffect): void;
  itemEffectGainTp(taget: IBattler, effect: ItemEffect): void;
  itemEffectAddState(taget: IBattler, effect: ItemEffect): void;
  itemEffectAddAttackState(taget: IBattler, effect: ItemEffect): void;
  itemEffectAddNormalState(taget: IBattler, effect: ItemEffect): void;
  itemEffectRemoveState(taget: IBattler, effect: ItemEffect): void;
  itemEffectAddBuff(taget: IBattler, effect: ItemEffect): void;
  itemEffectAddDebuff(taget: IBattler, effect: ItemEffect): void;
  itemEffectRemoveBuff(taget: IBattler, effect: ItemEffect): void;
  itemEffectRemoveDebuff(taget: IBattler, effect: ItemEffect): void;
  itemEffectSpecial(taget: IBattler, effect: ItemEffect): void;
  itemEffectGrow(taget: IBattler, effect: ItemEffect): void;

  itemEffectLearnSkill(taget: IBattler, effect: ItemEffect): void;
  makeSuccess(target: IBattler): void;
}
